"""PostgreSQL shared-store backend, for servers spread over several machines.

Requires the optional `psycopg` package (`pip install "psycopg[binary]"`).
"""

import threading

from opensnap.config import StorageConfig
from opensnap.storage.sql import Row


class PostgresqlConnection:
    """Thread-safe PostgreSQL connection implementing `SqlConnection`."""

    def __init__(self, config: StorageConfig) -> None:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError(
                'OPENSNAP_STORAGE_BACKEND=postgresql needs the psycopg package (pip install "psycopg[binary]").'
            ) from exc
        if not config.postgresql_host or not config.postgresql_user:
            raise ValueError(
                'OPENSNAP_POSTGRESQL_HOST and OPENSNAP_POSTGRESQL_USER are required for PostgreSQL storage.'
            )

        self.integrity_error = psycopg.IntegrityError
        self._psycopg = psycopg
        self._connect_arguments = {
            'host': config.postgresql_host,
            'port': config.postgresql_port,
            'user': config.postgresql_user,
            'password': config.postgresql_password,
            'dbname': config.postgresql_database,
            'autocommit': True,
            'row_factory': dict_row,
        }
        if config.postgresql_ssl_ca:
            self._connect_arguments.update(sslmode='verify-full', sslrootcert=config.postgresql_ssl_ca)
        self._lock = threading.Lock()
        self._connection = psycopg.connect(**self._connect_arguments)
        self._setup_schema()

    def execute(self, query: str, parameters: tuple[object, ...] = ()) -> None:
        self._run(query, parameters)

    def insert(self, query: str, parameters: tuple[object, ...] = (), *, key: str) -> int:
        rows = self._run(f'{query} RETURNING {key}', parameters, fetch=True)
        return int(rows[0][key])

    def insert_or_ignore(self, query: str, parameters: tuple[object, ...] = ()) -> None:
        self._run(f'{query} ON CONFLICT DO NOTHING', parameters)

    def query_one(self, query: str, parameters: tuple[object, ...] = ()) -> Row | None:
        rows = self._run(query, parameters, fetch=True)
        return rows[0] if rows else None

    def query_all(self, query: str, parameters: tuple[object, ...] = ()) -> list[Row]:
        return self._run(query, parameters, fetch=True)

    def close(self) -> None:
        with self._lock:
            self._connection.close()

    def _run(self, query: str, parameters: tuple[object, ...], *, fetch: bool = False) -> list[Row]:
        with self._lock:
            try:
                return self._send(query, parameters, fetch)
            except self._psycopg.OperationalError:
                # Servers stay idle for long periods; reconnect once if the
                # server dropped us (a statement on a lost connection never ran).
                if not (self._connection.closed or self._connection.broken):
                    raise
                self._connection = self._psycopg.connect(**self._connect_arguments)
                return self._send(query, parameters, fetch)

    def _send(self, query: str, parameters: tuple[object, ...], fetch: bool) -> list[Row]:
        with self._connection.cursor() as cursor:
            cursor.execute(_placeholders(query), parameters)
            return list(cursor.fetchall()) if fetch else []

    def _setup_schema(self) -> None:
        self.execute(
            'CREATE TABLE IF NOT EXISTS users ('
            'user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
            'username VARCHAR(255) NOT NULL UNIQUE, '
            'password TEXT NOT NULL, '
            'seed TEXT NOT NULL, '
            "team VARCHAR(255) NOT NULL DEFAULT ''"
            ')'
        )
        self.execute(
            'CREATE TABLE IF NOT EXISTS session_handoffs ('
            'serial BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
            'session_id BIGINT NOT NULL UNIQUE, '
            'user_id INTEGER NOT NULL, '
            'username VARCHAR(255) NOT NULL, '
            'host VARCHAR(255) NOT NULL, '
            'port INTEGER NOT NULL, '
            'game VARCHAR(255) NOT NULL, '
            'sequence_number BIGINT NOT NULL DEFAULT 0'
            ')'
        )
        self.execute('CREATE INDEX IF NOT EXISTS session_handoffs_endpoint ON session_handoffs (host, port)')
        self.execute(
            'CREATE TABLE IF NOT EXISTS records ('
            'record_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
            'game VARCHAR(64) NOT NULL, '
            'board VARCHAR(64) NOT NULL, '
            'user_id INTEGER NOT NULL, '
            'player VARCHAR(255) NOT NULL, '
            'score BIGINT NOT NULL, '
            'details TEXT NOT NULL, '
            'recorded_at VARCHAR(32) NOT NULL'
            ')'
        )
        self.execute('CREATE INDEX IF NOT EXISTS records_board ON records (game, board, score)')
        self.execute(
            'CREATE TABLE IF NOT EXISTS online_players ('
            'session_id BIGINT PRIMARY KEY, '
            'game VARCHAR(64) NOT NULL, '
            'user_id INTEGER NOT NULL, '
            'username VARCHAR(255) NOT NULL, '
            'host VARCHAR(255) NOT NULL, '
            'area_id BIGINT NOT NULL, '
            'login_serial BIGINT NOT NULL'
            ')'
        )
        self.execute('CREATE INDEX IF NOT EXISTS online_players_game ON online_players (game, login_serial)')


def _placeholders(query: str) -> str:
    """Translate the stores' `?` placeholders to psycopg's `%s`."""

    return query.replace('?', '%s')
