"""Command identifiers."""

CMD_LOGIN_TO_KICS = 0x01
CMD_CREATE_GAME_ROOM = 0x04
CMD_JOIN = 0x06
CMD_LEAVE = 0x07
CMD_CHANGE_ATTRIBUTE = 0x08
CMD_QUERY_ATTRIBUTE = 0x09
CMD_QUERY_USER = 0x0A
CMD_QUERY_GAME_ROOMS = 0x0B
CMD_CHANGE_USER_PROPERTY = 0x0C
CMD_CHANGE_USER_STATUS = 0x0D
CMD_QUERY_LOBBIES = 0x0E
CMD_SEND = 0x0F
CMD_SEND_TARGET = 0x10
CMD_SEND_ECHO = 0x14
CMD_LOGIN_CLIENT = 0x2C
CMD_BOOTSTRAP_LOGIN_SUCCESS = 0x2D
CMD_BOOTSTRAP_LOGIN_FAIL = 0x2E
CMD_BOOTSTRAP_LOGIN_SWAN = 0x40
CMD_BOOTSTRAP_LOGIN_SWAN_CHECK = 0x41
