"""Wire protocol constants."""

import struct

# Primary SNAP footer variant.
FOOTER_MARKER = 0xBA476611
FOOTER_BYTES = struct.pack('>L', FOOTER_MARKER)
# Alternate SNAP footer variant.
FOOTER_MARKER_KAGE = 0xBA476610
FOOTER_BYTES_KAGE = struct.pack('>L', FOOTER_MARKER_KAGE)

ACCEPTED_FOOTER_BYTES = (FOOTER_BYTES, FOOTER_BYTES_KAGE)

HEADER_SIZE = 16
FOOTER_SIZE = 4

TYPE_MASK = 0xFC00
LENGTH_MASK = 0x03FF

# Binary-verified from `kkSetMessage`/`kkSend*` builders and live packet traces.
FLAG_RELAY = 0x0400
FLAG_MULTI = 0x0800
FLAG_LOBBY = 0x1000
FLAG_RESPONSE = 0x4000
FLAG_RELIABLE = 0x8000

CHANNEL_ROOM = 0x2000
CHANNEL_MASK = CHANNEL_ROOM | FLAG_LOBBY
CHANNEL_LOBBY = CHANNEL_ROOM | FLAG_LOBBY
RELAY_CONTEXT_MASK = CHANNEL_MASK | FLAG_RELAY
TYPE_ROOM_RELAY = CHANNEL_ROOM | FLAG_RELAY
TYPE_LOBBY_RELAY = FLAG_LOBBY | FLAG_RELAY
